POST http://localhost:3000/api/carR
content-Type: application/json

{
        "Marca": "Toyota",
        "Modelo": "Corolla",
        "Ano": 2012,
        "Placa": "IHF1888",
        "Descrição": "Carro de estrada",
        "UserEmail": "debora.silveira@outlook.com"
}

###
GET http://localhost:3000/api/carR/debora.silveira@outlook.com

###
DELETE http://localhost:3000/api/carR/viniciusbandeira@rede.ulbra.br/S10/1998/asdw848

###
POST http://localhost:3000/api/userR
content-Type: application/json

{
        "Email": "roberto@outlook.com",
        "Name": "Roberto do Santos Rocha",
        "ImageURL": "http//asdqwe"
}

###
GET http://localhost:3000/api/userR/viniciusbandeira@rede.ulbra.br

